### ISSUE TITLE
直接运行demo报错了（cURL error 3: <url> malformed）

### ISSUE THREAD

**Issue by imzhi** [Hanson/weibot#1]
下面是报错：
```shell
$ /usr/bin/php7.1 login.php
PHP Notice:  Undefined index: crossDomainUrlList in /home/yxz/samba_share/project/weibot_test/vendor/hanson/weibot/src/Auth/Auth.php on line 80
PHP Stack trace:
PHP   1. {main}() /home/yxz/samba_share/project/weibot_test/login.php:0
PHP   2. Hanson\Weibot\Weibot->login() /home/yxz/samba_share/project/weibot_test/login.php:12
PHP   3. Hanson\Weibot\Auth\Auth->login() /home/yxz/samba_share/project/weibot_test/vendor/hanson/weibot/src/Weibot.php:35
PHP   4. Hanson\Weibot\Auth\Auth->sinaLogin() /home/yxz/samba_share/project/weibot_test/vendor/hanson/weibot/src/Auth/Auth.php:29
PHP Fatal error:  Uncaught GuzzleHttp\Exception\RequestException: cURL error 3: <url> malformed (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /home/yxz/samba_share/project/weibot_test/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:201
Stack trace:
#0 /home/yxz/samba_share/project/weibot_test/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /home/yxz/samba_share/project/weibot_test/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /home/yxz/samba_share/project/weibot_test/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /home/yxz/samba_share/project/weibot_test/ven in /home/yxz/samba_share/project/weibot_test/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 201
```

这是我运行的源码：
```php
<?php

use Hanson\Weibot\Api\Api;

include_once __DIR__.'/vendor/autoload.php';
$weibo = new \Hanson\Weibot\Weibot([
    'username' => 'imzhi',
    'password' => 'anzhan0511',
    'cookie_path' => __DIR__.'/cookie',
    'debug' => []
]);
$follow = $weibo->login()->follow;

// $follow = $weibo->follow;

// $follow->getData([
//     'page' => 1, // 页数
// ]);
// var_dump($follow);
```

关键异常是：``PHP Fatal error:  Uncaught GuzzleHttp\Exception\RequestException: cURL error 3: <url> malformed``，请看下啥原因？

**Comment by hldh214** [comment]
https://github.com/Hanson/weibot/blob/d716477103f18b15a960260deb48efdec67d4145/src/Auth/Auth.php#L77-L82

这里的 `$result` 你打出来瞧瞧就知道为什么了

**Comment by Hanson** [comment]
打印一下 $result 值

**Comment by yeless** [comment]
打印一下 $result 值

**Comment by yeless** [comment]
打印一下 $result 值瞧一瞧

**Comment by imzhi** [comment]
是我密码弄错了…

打印代码：
```
var_dump('result ==>', $result);
```

结果：
```
/home/yxz/samba_share/project/weibot_test/vendor/hanson/weibot/src/Auth/Auth.php:79:string(10) "result ==>"
/home/yxz/samba_share/project/weibot_test/vendor/hanson/weibot/src/Auth/Auth.php:79:
array(2) {
  'retcode' =>  string(3) "101"
  'reason' =>
  string(24) "登录名或密码错误"
}
```

**Comment by imzhi** [comment]
`换了正确的密码可以了

**Comment by Hanson** [comment]
fix https://github.com/Hanson/weibot/commit/2116b236545f83142dd4246f2cbcab308685d5e7
